### ISSUE TITLE
[BUG] Crash on Launching in 1.18.2

### ISSUE THREAD

**Issue by Phoupraw** [teddyxlandlee/enchlevel-langpatch#1]
[crash-2022-05-18_22.33.13-client.txt](https://github.com/teddyxlandlee/enchlevel-langpatch/files/8717164/crash-2022-05-18_22.33.13-client.txt)

**Comment by teddyxlandlee** [comment]
OK I'll go and check.

**Comment by teddyxlandlee** [comment]
Confirmed.  
Mojang added a parameter (`java.util.function.Function`) to `DefaultedRegistry.<init>` since 1.18.2 (some snapshot between 1.18.1 and 1.18.2), making the original one unaccessible.  
I will try to create a new class instead of `DefaultedRegistry`. This thing has already caused incompability issues around 1.16.1.

**Comment by teddyxlandlee** [comment]
Fixed in 1.0.0.
*WARNING: Java API implementations in 0.x is COMPLETELY NOT COMPATIBLE with 1.x*
