### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by Devc2** [teddyxlandlee/enchlevel-langpatch#5]
i dont know why but the config file isn't building when i start mc
lang patch: 2.1.0
mc version: 1.19.4
w/Lan patch config: 4.0.0

**Comment by Devc2** [comment]
and i can't change the format to roman instead of default format

**Comment by teddyxlandlee** [comment]
I'm sorry that I might haven't pointed out clearly that **the way to change to roman format has changed** since LangPatch 2.1.0.

In short, you can to install this resource pack **with** the latest version of LangPatch to solve the problem.

[roman-numbers.zip](https://github.com/teddyxlandlee/enchlevel-langpatch/files/11332017/roman-numbers.zip)

In addition, the config mod is now **not mandatory** if you want to switch to roman format.

Sorry for your inconvenience.

===================================

Since 2.1.0, the way to change to roman format has changed from installing the config mod **to modify several translation values**:

- `langpatch.conf.enchantment.default.type`, which controls enchantment format (under `default` patch).
- `langpatch.conf.potion.default.type`, which controls potion potency format (under `default` patch).

Acceptable values are (Examples of `123`):

- `numeral` / `number` / `numeric` / `arabic` / `default`: Numeral format (`123`)
- `roman`: Roman format (`CXXIII`)
- `simplified` / `chinese` / `zh_normal`: Simplified Chinese (`一百二十三`)
- `traditional` / `zh_upper`: Traditional Chinese, uppercase (`壹佰貳拾叄`)

Please note that `default` and `roman` **in the legacy config mod** are now **identical**, the latter one becoming deprecated.

Here's an example for `assets/<any_namespace>/lang/en_us.json`:
```json
{
  "langpatch.conf.enchantment.default.type": "roman",
  "langpatch.conf.potion.default.type": "roman"
} 
```
This changes both enchantment and potion potency format into roman format.

**Comment by Devc2** [comment]
ah
